/**
 * Copyright (c) Jonas Franke and the ContentKit Contributors
 * SPDX-License-Identifier: BSD-3-Clause
 */

import type { ContentKitConfig, FieldType } from "@ckjs/types";

function getFieldTypeString(fieldType: FieldType): string {
  if (fieldType.type === "date") {
    return "Date";
  } else if (fieldType.type === "array" || fieldType.type === "list") {
    const itemType = fieldType.items
      ? getFieldTypeString(fieldType.items)
      : "any";
    return `${itemType}[]`;
  } else if (fieldType.type === "object") {
    if (fieldType.fields) {
      const fields = Object.entries(fieldType.fields)
        .map(([key, ft]) => {
          const type = getFieldTypeString(ft);
          const optional = ft.required ? "" : " | undefined";
          return `${key}: ${type}${optional}`;
        })
        .join("; ");
      return `{ ${fields} }`;
    }
    return "Record<string, any>";
  } else {
    return fieldType.type;
  }
}

export function generateTypeScriptTypesFile(
  config: ContentKitConfig,
  typesDir: string,
): string {
  const documentTypes = config.documentTypes
    .map(
      (docType) =>
        `export type ${docType.name} = {\n  _id: string;\n  _raw: any;\n  type: '${docType.name}';\n  raw: string;\n  html: string;\n  ${Object.entries(
          docType.fields,
        )
          .map(([fieldName, fieldType]) => {
            const type = getFieldTypeString(fieldType);
            const optional = fieldType.required ? "" : " | undefined";
            return `${fieldName}: ${type}${optional};`;
          })
          .join("\n  ")}\n  ${Object.entries(docType.computedFields || {})
          .map(([fieldName, field]) => `${fieldName}: ${field.type};`)
          .join("\n  ")}\n};`,
    )
    .join("\n\n");

  const documentTypeNames = config.documentTypes
    .map((docType) => `'${docType.name}'`)
    .join(" | ");
  const documentTypesUnion = config.documentTypes
    .map((docType) => docType.name)
    .join(" | ");

  return `// NOTE This file is auto-generated by ContentKit

${documentTypes}

export type DocumentTypes = ${documentTypesUnion};
export type DocumentTypeNames = ${documentTypeNames};

export type DataExports = {
  ${config.documentTypes.map((docType) => `all${docType.name}s: ${docType.name}[]`).join(";\n  ")};
  allDocuments: DocumentTypes[];
};
`;
}
