/**
 * Copyright (c) Jonas Franke and the ContentKit Contributors
 * SPDX-License-Identifier: ICL
 */

import type { ContentKitConfig } from "@ckjs/types";

export function generateIndexTypesFile(config: ContentKitConfig): string {
  const exports = config.documentTypes
    .map(
      (docType) =>
        `export declare const all${docType.name}s: ${docType.name}[];`,
    )
    .join("\n");

  return `// NOTE This file is auto-generated by ContentKit

import { ${config.documentTypes.map((docType) => docType.name).join(", ")}, DocumentTypes } from './types';

export * from './types';

${exports}

export declare const allDocuments: DocumentTypes[];
`;
}
