/**
 * Copyright (c) Jonas Franke and the ContentKit Contributors
 * SPDX-License-Identifier: ICL
 */

import type { ContentKitConfig } from "@ckjs/types";

export function generateIndexFile(
  config: ContentKitConfig,
  cacheDir: string,
  isESM: boolean,
): string {
  const imports = [];
  const exports = [];
  const allDocuments = [];

  for (const docType of config.documentTypes) {
    const variableName = `all${docType.name}s`;
    const importPath = `./${docType.name}/_index.json`;

    if (isESM) {
      imports.push(
        `import ${variableName} from '${importPath}' with { type: 'json' };`,
      );
      exports.push(`export { ${variableName} };`);
    } else {
      imports.push(`const ${variableName} = require('${importPath}');`);
      exports.push(`exports.${variableName} = ${variableName};`);
    }

    allDocuments.push(`...${variableName}`);
  }

  const allDocumentsExport = isESM
    ? `export const allDocuments = [${allDocuments.join(", ")}];`
    : `exports.allDocuments = [${allDocuments.join(", ")}];`;

  return `// NOTE: This file is auto-generated by ContentKit

${imports.join("\n")}

${exports.join("\n")}

${allDocumentsExport}
`;
}
