name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Publish mode (canary or stable)"
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - canary

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "master"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Verify versions
        run: pnpm scripts:uv

      - name: Build packages
        run: pnpm build

      - name: Prepare packages
        run: |
          if [ "${{ github.event.inputs.mode }}" = "canary" ]; then
            pnpm scripts:prepare --canary
          else
            pnpm scripts:prepare
          fi

      - name: Publish packages
        run: |
          pnpm m ls --json --depth=-1 | jq -r '.[].path' | grep '/packages/' | while read -r package; do
            echo "Publishing package: $package"
            cd "$package"

            if [ "${{ github.event.inputs.mode }}" = "canary" ]; then
              npm publish --access public --tag canary --provenance --no-git-checks
            else
              npm publish --access public --provenance --no-git-checks
            fi

            cd -
          done

      - name: Create GitHub Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          TAG="v$VERSION"

          if [ "${{ github.event.inputs.mode }}" = "canary" ]; then
            IS_PRERELEASE=true
          else
            IS_PRERELEASE=false
          fi

          gh release create "$TAG" \
            --title "$TAG" \
            --notes-file CHANGELOG.md \
            --prerelease=$IS_PRERELEASE
